name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Digital-Ocean
    runs-on: ubuntu-latest    
    steps:
      - uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          run: touch test
      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.1.0
        with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
       
      - name: test
        run: doctl compute ssh test

     
