name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Digital-Ocean
    runs-on: ubuntu-latest    
    steps:
      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.1.0
        with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: test
        run: |
          cat <<EOF  > .id_rsa.pub   
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqkrmWHCexSo+4cjcpWS3e9n8JF5f5CdkcRvg9vFN8iTsdYlAKlYWWnZ7ggXrITMnIbiQjehfrK0/l3R3v8532uN4hX1BvQueNROGI9KeE6s+X6U+hFburGrLGjfXYgvqIXU5AZd4LjcJq5XZ9niC7DliYEEdLiq8n664BKNgyHVYCgR1N/kyeEigmwos581HNVn5biNjLqgXOtKYr8BDdl8cog9EGhHBOwqQ0nO8G+/gM6yynqjxcOqYgEKkmqRnJXSr2cJqEO9E3EP+aRRUmCtDBEWmGwUI8sLl9sD/1ivQ8KbN8UJvJHXdz3H+ZnUaVq06SaDcBxvxKTCmvydA9 root@build-final
          EOF
          chmod 655 .id_rsa.pub
          IPaddress=$(doctl compute droplet list mydroplet | awk 'NR==2 {print $3}')
          echo "$IPaddress"
          ssh -o StrictHostKeyChecking=no -i .id_rsa root@$IPaddress "sh /root/script"
