name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Digital-Ocean
    runs-on: ubuntu-latest    
    steps:
      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.1.0
        with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: test
        run: |
          IPaddress=$(doctl compute droplet list mydroplet | awk 'NR==2 {print $3}')
          ssh -o StrictHostKeyChecking=no -i file root@IPaddress "touch /root/filesri"
