name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Digital-Ocean
    runs-on: ubuntu-latest    
    steps:
      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.1.0
        with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: test
        run: |
          echo "           
          ---BEGIN OPENSSH PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
          NhAAAAAwEAAQAAAYEA9Bmizz1vlQCNSysOPPobtOLVdKnTO2vyiPCK14xyugD3ltPL1myT
          j4lzapuOb3mjoJqpQG+0zU2GoIqBIAhkHfXXkXTSlS9SWtw65nnpryiPi1YSWRR84tx85O
          wtoa9c5uuEgJG/e3KlimZ2YcGtpINZJlQpLaRhm65fmS+BYLDxpb2kMrHxAwb4sKlWY0qn
          IJrD2qcduMN9zXD1XYRNUVAQM6Re7bkhio6Yvz+8nlpFNCIJ//VytOUME+XXg62gWTgZPQ
          y/SFAxlN88YBpFpD7k/SG4FklQumiQmw1wbT7Fix6byk6QZmI4Ckk+KO0P1/FA8n/32I/I
          PRbw7IZW5KAAU/7eJBy8A9Xxtv8vOAifQcUCJ/Ge/C0yOm00tFAK1/5ZX5oRzpLaIbaRIu
          SlHY30U8zI7Dz21TxDOWqAGBlzxLHPuKB4zfCdtP1sQpz5Y97WmSIsME+eMbUcdGKp7O1u
          za2X3+ztsVUlD56fphUM8xOc5q1exNPB01VfMcB9AAAFoBb9+F8W/fhfAAAAB3NzaC1yc2
          EAAAGBAPQZos89b5UAjUsrDjz6G7Ti1XSp0ztr8ojwiteMcroA95bTy9Zsk4+Jc2qbjm95
          o6CaqUBvtM1NhqCKgSAIZB3115F00pUvUlrcOuZ56a8oj4tWElkUfOLcfOTsLaGvXObrhI
          CRv3typYpmdmHBraSDWSZUKS2kYZuuX5kvgWCw8aW9pDKx8QMG+LCpVmNKpyCaw9qnHbjD
          fc1w9V2ETVFQEDOkXu25IYqOmL8/vJ5aRTQiCf/1crTlDBPl14OtoFk4GT0Mv0hQMZTfPG
          AaRaQ+5P0huBZJULpokJsNcG0+xYsem8pOkGZiOApJPijtD9fxQPJ/99iPyD0W8OyGVuSg
          AFP+3iQcvAPV8bb/LzgIn0HFAifxnvwtMjptNLRQCtf+WV+aEc6S2iG2kSLkpR2N9FPMyO
          w89tU8QzlqgBgZc8Sxz7igeM3wnbT9bEKc+WPe1pkiLDBPnjG1HHRiqeztbs2tl9/s7bFV
          JQ+en6YVDPMTnOatXsTTwdNVXzHAfQAAAAMBAAEAAAGAVwtVPWWBBrc9q1JdL21Yt/Yze/
          ibNJNX13E/cYHJ3348y/IWvA3XyNWQ7LEv55yOttSwCiRLavJ8UX9ScGPNn8ls55erCDvp
          uDDUaB+NL0LdfShiPpXJuvQ5LUDzPLbWABp4E4jlqVXGpkXHbTCthP65qatVS8tUazmRKY
          UBM8OlSB8KEHHXqeawg/6+qYWTd1L5CF2TgbFkiQAA3yowkBBm1qOEnmzoAwq6eWh3EFjM
          WLzSqA2Uq+EJn4bUhUZCN38XXuwwHTJEO3iZMfDszUzgaDaISOX5gfOiL2OCsiGYDhjXnL
          X1o3Lw8f5RqWhkeKjvBS73kRx7mQnsWh+B5tnVflLcAVJmxgaa1bIQdqpmEX7kUMsyAtrW
          8uk+oi7/WwnHZsfR9TeQeldxNl50lQzqWPJcC/6nxEXtGnJelrDA+RbyYtlw4b3m4swFq2
          vqwoiqHoErNHijol4Ws6RjqqpEOL/rh9qf/FuAFE9Cz5/DUUbU8tBTYIM8qsiXxvNZAAAA
          wGpo+JsCWJ+bG4cfDBSt4hdSKkisPB9N11PBDt+Yw+lf164yLCr5PY+1DheJGz8YhsyMSd
          3JlbLcQwH+0VT1mSWGcIKWXjjcNBGRdhT/AmAUUOlWZIVlhNgQjsd1rudo8VGgwBOimqT6
          a+59d5YgPTHJDsmiMCL6zsA+gmkLjEjMf12J9spUkIUGZ/OiTjHf4dIS/gLI0HuWIkdvdL
          4JBsP5Xpc1i25r2g+/fKtQY4MfbFBIa5e8U5ShkKIp7n+bhgAAAMEA/kqzWHdqaiKTxUNK
          Aq4EVb5Chf8kJx07f6ntlsjDmwtCAE5fJJGoz8lZ+hBE+vPpnZ1vtssbwx7cglnEt7WiJn
          er2+7GaJJAYZwjxZX7Ti1SoyCegRI/ERd66AuYJJUFiYYOz5u/h5rewXygfYgH/8cthZ36
          K03gncYg8hdS3G+GldLvXLuLZVT1SWEUeaBdw0PcMhI+mC/j54vTdx66axjECt2D9PFmi9
          AeZx5+9ZJgMndkL5bixDdLDGOInEyTAAAAwQD1vWi4DF7daD/qEMFT9QVzSk4P6gbZp8Bm
          nWDXjnY1Eh+T1HJOWZFoMFDrRWYy7IgJlnHBSEX3YdcNmhUBOPIxKGRUN4CbMxxv191Gjy
          V9YOkoFcoTw0d9ZuOUXgukuQ3UGVA7CoQsWux6q7GHortxaA0W0s2h52ZIIxuXqzy7jOxl
          Zs1SoP4GL9FWb+3t/p8bGgo1KaE/TxIWcEG3+p2aFYc24dIQSnc686MK6569q8773vPAV1
          TMjM71VTsJ+K8AAAAkc3JpZWRqeEBTcmVla2FudGhzLU1hY0Jvb2stUHJvLmxvY2FsAQID
          BAUGBw==
          -----END OPENSSH PRIVATE KEY-----" > file          
           cat file
           chmod 400 file
           ssh -o StrictHostKeyChecking=no -i file root@139.59.10.237
           ls
           pwd
