name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Digital-Ocean
    runs-on: ubuntu-latest    
    steps:
      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.1.0
        with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: test
        run: |
          cat <<EOF  > file   
          8uk+oi7/WwnHZsfR9TeQeldxNl50lQzqWPJcC/6nxEXtGnJelrDA+RbyYtlw4b3m4swFq2
          vqwoiqHoErNHijol4Ws6RjqqpEOL/rh9qf/FuAFE9Cz5/DUUbU8tBTYIM8qsiXxvNZAAAA
          wGpo+JsCWJ+bG4cfDBSt4hdSKkisPB9N11PBDt+Yw+lf164yLCr5PY+1DheJGz8YhsyMSd
          JBsP5Xpc1i25r2g+/fKtQY4MfbFBIa5e8U5ShkKIp7n+bhgAAAMEA/kqzWHdqaiKTxUN
          EOF
          cat file

           
