name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Digital-Ocean
    runs-on: ubuntu-latest    
    steps:
      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.1.0
        with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: test
        run: doctl compute droplet list --format "ID,Name,PublicIPv4"
      - name: create
        run: doctl compute droplet create --image 80959838 --size s-2vcpu-4gb --region blr1 --ssh-keys ${{ secrets.SSH }} --ssh-command "touch /root/file" test
