name: edjos build automation
on: push

jobs:
  build:
    name: Digital-Ocean
    runs-on: ubuntu-latest    
    steps:
      - name: Digital Ocean Auth
        uses: digitalocean/action-doctl@v2.1.0
        with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: edjos droplet
        run: doctl compute droplet create --image 82170717 --size s-2vcpu-4gb --region nyc3 --ssh-keys ${{ secrets.SSH }} mydroplet
      - name: sleep
        run: sleep 500
