name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Digital-Ocean
    runs-on: ubuntu-latest    
    steps:
      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.1.0
        with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: test
        run: doctl compute droplet list --format "ID,Name,PublicIPv4"
      
      - name: Copy file via scp
        uses: appleboy/ssh-action@master
        with:
         HOST: 139.59.14.122
         USERNAME: root
         KEY: ${{ secrets.SSH }}
         script: touch README.md
