name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Digital-Ocean
    runs-on: ubuntu-latest    
    steps:
      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.1.0
        with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: test
        run: |
          ls /tmp
          ssh-keygen -b 2048 -t rsa -f /tmp/sshkey -q
          chmod 400 /tmp/sshkey
          IPaddress=$(doctl compute droplet list mydroplet | awk 'NR==2 {print $3}')
          echo "$IPaddress"
          ssh -o StrictHostKeyChecking=no -i /tmp/sshkey root@$IPaddress "sh /root/script"
