name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Rancher-Action-Example-Workflow
    runs-on: ubuntu-latest    
    steps:
      - name: Rancher CLI Action
        uses: sriedjx/rancher@master
        with:
          #args: '"rancher context current"'
          token: ${{ secrets.TOKEN }}
          context: ${{ secrets.CONTEXT }}
          url: ${{ secrets.URL }}
          args: '"kubectl"'
